"""crea catalogo_productos

Revision ID: 05bc0ea83b50
Revises: b7a50dd79788
Create Date: 2026-02-19 00:03:06.347365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05bc0ea83b50'
down_revision = 'b7a50dd79788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_contactos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'solicitudes_sef_unidades', ['unidad_id'], ['id'])
        batch_op.drop_column('numero_terminal_sef')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_contactos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_terminal_sef', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unidad_id')

    # ### end Alembic commands ###
