"""catalogos base

Revision ID: 0a6ff328fd66
Revises: 4105d279633d
Create Date: 2026-02-15 19:08:20.851757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6ff328fd66'
down_revision = '4105d279633d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_cpae', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abreviatura', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_cpae', schema=None) as batch_op:
        batch_op.drop_column('abreviatura')

    # ### end Alembic commands ###
