"""crea catalogo_productos

Revision ID: 17b949962f8d
Revises: dbde8fa1d54f
Create Date: 2026-02-18 22:56:42.893219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b949962f8d'
down_revision = 'dbde8fa1d54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('css', sa.Text(), nullable=False),
    sa.Column('cascaron', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'version', name='uq_document_templates_slug_version')
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.create_index('idx_document_templates_active', ['slug'], unique=False, postgresql_where=sa.text('is_active = TRUE'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index('idx_document_templates_active', postgresql_where=sa.text('is_active = TRUE'))

    op.drop_table('document_templates')
    # ### end Alembic commands ###
