"""crea tabla solicitudes

Revision ID: 204c66c9cef9
Revises: 6a807ac4c407
Create Date: 2026-02-14 01:16:58.316229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '204c66c9cef9'
down_revision = '6a807ac4c407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=50), nullable=False),
    sa.Column('estado_actual', sa.String(length=50), nullable=False),
    sa.Column('estatus', sa.String(length=20), nullable=False),
    sa.Column('usuario_creador', sa.String(length=50), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_estatus'), ['estatus'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_producto'), ['producto'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_producto'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_estatus'))

    op.drop_table('solicitudes')
    # ### end Alembic commands ###
