"""crea catalogo_productos

Revision ID: 29dd4d871758
Revises: 7ab4c50c7ed1
Create Date: 2026-02-21 00:46:03.240522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dd4d871758'
down_revision = '7ab4c50c7ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarifas_comision_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_comision', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarifas_comision_producto', schema=None) as batch_op:
        batch_op.drop_column('nombre_comision')

    # ### end Alembic commands ###
