"""fix relaciones sef

Revision ID: 2e46ee2bced6
Revises: 6b8754414cdd
Create Date: 2026-02-14 19:07:37.975922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e46ee2bced6'
down_revision = '6b8754414cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_unidades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('solicitudes_sef_unidades_solicitud_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'solicitudes_sef', ['solicitud_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_unidades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solicitudes_sef_unidades_solicitud_id_fkey'), 'solicitudes', ['solicitud_id'], ['id'])

    # ### end Alembic commands ###
