"""crea catalogo_productos

Revision ID: 3c3c90cfe9f1
Revises: 204c66c9cef9
Create Date: 2026-02-14 08:26:28.736820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3c90cfe9f1'
down_revision = '204c66c9cef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogo_productos_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_productos_code'))

    op.drop_table('catalogo_productos')
    # ### end Alembic commands ###
