"""agrega campos base solicitud

Revision ID: 3f296f7d85ce
Revises: 6b38fbda5057
Create Date: 2026-02-14 17:40:01.344026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f296f7d85ce'
down_revision = '6b38fbda5057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cortes_envio', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef', schema=None) as batch_op:
        batch_op.drop_column('cortes_envio')

    # ### end Alembic commands ###
