"""catalogos base

Revision ID: 4105d279633d
Revises: a610ec5a57a5
Create Date: 2026-02-15 18:29:15.038776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4105d279633d'
down_revision = 'a610ec5a57a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_cpae',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_entidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave_inegi', sa.String(length=5), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_etv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave_inegi', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entidad_id'], ['catalogo_entidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_procesadora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('etv_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['etv_id'], ['catalogo_etv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_sef_unidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpae_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('etv_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('procesadora_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('entidad_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('municipio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'catalogo_etv', ['etv_id'], ['id'])
        batch_op.create_foreign_key(None, 'catalogo_cpae', ['cpae_id'], ['id'])
        batch_op.create_foreign_key(None, 'catalogo_procesadora', ['procesadora_id'], ['id'])
        batch_op.create_foreign_key(None, 'catalogo_entidad', ['entidad_id'], ['id'])
        batch_op.create_foreign_key(None, 'catalogo_municipio', ['municipio_id'], ['id'])
        batch_op.drop_column('cpae_unidad')
        batch_op.drop_column('procesadora_unidad')
        batch_op.drop_column('municipio')
        batch_op.drop_column('etv_unidad')
        batch_op.drop_column('entidad_federativa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_unidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entidad_federativa', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('etv_unidad', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('municipio', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('procesadora_unidad', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cpae_unidad', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('municipio_id')
        batch_op.drop_column('entidad_id')
        batch_op.drop_column('procesadora_id')
        batch_op.drop_column('etv_id')
        batch_op.drop_column('cpae_id')

    op.drop_table('catalogo_procesadora')
    op.drop_table('catalogo_municipio')
    op.drop_table('catalogo_etv')
    op.drop_table('catalogo_entidad')
    op.drop_table('catalogo_cpae')
    # ### end Alembic commands ###
