"""crea catalogo_productos

Revision ID: 5c9f37c9cc6a
Revises: fe6a80402a6b
Create Date: 2026-02-21 00:11:10.438839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9f37c9cc6a'
down_revision = 'fe6a80402a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarifas_comision_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_comision', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['catalogo_productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarifas_comision_producto', schema=None) as batch_op:
        batch_op.create_index('idx_tarifa_comision_producto_activo', ['producto_id', 'tipo_comision'], unique=False, postgresql_where=sa.text('activo = TRUE'))
        batch_op.create_index(batch_op.f('ix_tarifas_comision_producto_producto_id'), ['producto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarifas_comision_producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarifas_comision_producto_producto_id'))
        batch_op.drop_index('idx_tarifa_comision_producto_activo', postgresql_where=sa.text('activo = TRUE'))

    op.drop_table('tarifas_comision_producto')
    # ### end Alembic commands ###
