"""initial

Revision ID: 6a807ac4c407
Revises: 
Create Date: 2026-02-14 01:11:32.067567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a807ac4c407'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_fullname'), ['fullname'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permisos_code'), ['code'], unique=True)

    op.create_table('role_product_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('producto_code', sa.String(length=50), nullable=False),
    sa.Column('habilitado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_product_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_product_access_producto_code'), ['producto_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_product_access_role'), ['role'], unique=False)

    op.create_table('role_permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permiso_code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['permiso_code'], ['permisos.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permiso_code', name='uq_role_permiso')
    )
    with op.batch_alter_table('role_permisos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permisos_permiso_code'), ['permiso_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permisos_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role_permisos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permisos_role'))
        batch_op.drop_index(batch_op.f('ix_role_permisos_permiso_code'))

    op.drop_table('role_permisos')
    with op.batch_alter_table('role_product_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_product_access_role'))
        batch_op.drop_index(batch_op.f('ix_role_product_access_producto_code'))

    op.drop_table('role_product_access')
    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permisos_code'))

    op.drop_table('permisos')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))
        batch_op.drop_index(batch_op.f('ix_admin_users_role'))
        batch_op.drop_index(batch_op.f('ix_admin_users_fullname'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
