"""agrega campos base solicitud

Revision ID: 6b38fbda5057
Revises: 93ccfc702436
Create Date: 2026-02-14 11:51:11.576363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b38fbda5057'
down_revision = '93ccfc702436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_sef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=100), nullable=True),
    sa.Column('tipo_servicio', sa.String(length=150), nullable=True),
    sa.Column('servicio_adicional', sa.String(length=150), nullable=True),
    sa.Column('tipo_cobro', sa.String(length=50), nullable=True),
    sa.Column('importe_maximo_dif', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('segmento', sa.String(length=50), nullable=True),
    sa.Column('tipo_persona', sa.String(length=150), nullable=True),
    sa.Column('apoderado_legal', sa.String(length=150), nullable=True),
    sa.Column('correo_apoderado_legal', sa.String(length=150), nullable=True),
    sa.Column('telefono_cliente', sa.String(length=20), nullable=True),
    sa.Column('domicilio_cliente', sa.String(length=250), nullable=True),
    sa.Column('sust_mod_unidades', sa.Boolean(), nullable=True),
    sa.Column('sust_mod_cuentas', sa.Boolean(), nullable=True),
    sa.Column('sust_mod_usuarios', sa.Boolean(), nullable=True),
    sa.Column('sust_mod_contactos', sa.Boolean(), nullable=True),
    sa.Column('sust_mod_tipocobro', sa.Boolean(), nullable=True),
    sa.Column('sust_mod_impdif', sa.Boolean(), nullable=True),
    sa.Column('sust_crea_unidades', sa.Boolean(), nullable=True),
    sa.Column('sust_crea_cuentas', sa.Boolean(), nullable=True),
    sa.Column('sust_crea_usuarios', sa.Boolean(), nullable=True),
    sa.Column('sust_crea_contactos', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitud_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_sef')
    # ### end Alembic commands ###
