"""agrega campos base solicitud

Revision ID: 6b8754414cdd
Revises: 3f296f7d85ce
Create Date: 2026-02-14 18:28:22.842486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8754414cdd'
down_revision = '3f296f7d85ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_sef_unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('accion_unidad', sa.String(length=20), nullable=True),
    sa.Column('nombre_unidad', sa.String(length=150), nullable=True),
    sa.Column('cpae_unidad', sa.String(length=50), nullable=True),
    sa.Column('etv_unidad', sa.String(length=50), nullable=True),
    sa.Column('procesadora_unidad', sa.String(length=50), nullable=True),
    sa.Column('servicio_verificacion_tradicional', sa.Boolean(), nullable=False),
    sa.Column('servicio_verificacion_electronica', sa.Boolean(), nullable=False),
    sa.Column('servicio_cliente_certificado_central', sa.Boolean(), nullable=False),
    sa.Column('servicio_dotacion_centralizada', sa.Boolean(), nullable=False),
    sa.Column('servicio_integradora', sa.Boolean(), nullable=False),
    sa.Column('servicio_dotacion', sa.Boolean(), nullable=False),
    sa.Column('servicio_traslado', sa.Boolean(), nullable=False),
    sa.Column('servicio_cofre', sa.Boolean(), nullable=False),
    sa.Column('cofre_modelo', sa.String(length=50), nullable=True),
    sa.Column('relacion_dot_centralizada', sa.String(length=50), nullable=True),
    sa.Column('relacion_cc_centralizada', sa.String(length=50), nullable=True),
    sa.Column('calle_numero', sa.String(length=255), nullable=True),
    sa.Column('municipio', sa.Integer(), nullable=True),
    sa.Column('entidad_federativa', sa.Integer(), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_sef_unidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_sef_unidades_solicitud_id'), ['solicitud_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_unidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_sef_unidades_solicitud_id'))

    op.drop_table('solicitudes_sef_unidades')
    # ### end Alembic commands ###
