"""crea catalogo_productos

Revision ID: 726ac4f51b69
Revises: 05bc0ea83b50
Create Date: 2026-02-19 00:14:45.462398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726ac4f51b69'
down_revision = '05bc0ea83b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_usuarios_sef', schema=None) as batch_op:
        batch_op.drop_column('estatus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_usuarios_sef', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estatus', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
