"""catalogos base

Revision ID: 7a3c6534a4c3
Revises: bb9b3ff8a7eb
Create Date: 2026-02-16 21:57:54.057578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3c6534a4c3'
down_revision = 'bb9b3ff8a7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_sef_cuentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sef_id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=True),
    sa.Column('sucursal', sa.String(length=10), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=20), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('tipo_cuenta', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['sef_id'], ['solicitudes_sef.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidad_id'], ['solicitudes_sef_unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_sef_cuentas')
    # ### end Alembic commands ###
