"""crea catalogo_productos

Revision ID: 7ab4c50c7ed1
Revises: 5c9f37c9cc6a
Create Date: 2026-02-21 00:40:11.900082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab4c50c7ed1'
down_revision = '5c9f37c9cc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarifas_comision_producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tarifa_comision_producto_activo'), postgresql_where='(activo = true)')
        batch_op.create_index('idx_tarifa_comision_producto_activo', ['producto_id'], unique=False, postgresql_where=sa.text('activo = TRUE'))
        batch_op.drop_column('tipo_comision')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarifas_comision_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_comision', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_index('idx_tarifa_comision_producto_activo', postgresql_where=sa.text('activo = TRUE'))
        batch_op.create_index(batch_op.f('idx_tarifa_comision_producto_activo'), ['producto_id', 'tipo_comision'], unique=False, postgresql_where='(activo = true)')

    # ### end Alembic commands ###
