"""crea catalogo_productos

Revision ID: 88006ef60e31
Revises: 9bb5e78aa60a
Create Date: 2026-02-19 08:40:40.568765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88006ef60e31'
down_revision = '9bb5e78aa60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_sef_firmantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sef_id', sa.Integer(), nullable=False),
    sa.Column('puesto', sa.String(length=150), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('soeid', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['catalogo_productos.id'], ),
    sa.ForeignKeyConstraint(['sef_id'], ['solicitudes_sef.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_sef_firmantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_sef_firmantes_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_sef_firmantes_sef_id'), ['sef_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_firmantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_sef_firmantes_sef_id'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_sef_firmantes_producto_id'))

    op.drop_table('solicitudes_sef_firmantes')
    # ### end Alembic commands ###
