"""crea catalogo_productos

Revision ID: 93ccfc702436
Revises: b5145fa8c6b8
Create Date: 2026-02-14 10:58:00.165106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ccfc702436'
down_revision = 'b5145fa8c6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_tramite', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('tipo_tramite')

    # ### end Alembic commands ###
