"""crea catalogo_productos

Revision ID: 9bb5e78aa60a
Revises: 726ac4f51b69
Create Date: 2026-02-19 00:46:00.248100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb5e78aa60a'
down_revision = '726ac4f51b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_perfiles_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['catalogo_productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_perfiles_producto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogo_perfiles_producto_producto_id'), ['producto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_perfiles_producto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_perfiles_producto_producto_id'))

    op.drop_table('catalogo_perfiles_producto')
    # ### end Alembic commands ###
