"""crea catalogo_productos

Revision ID: 9e2cdc50ca43
Revises: 17b949962f8d
Create Date: 2026-02-18 23:00:16.093064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2cdc50ca43'
down_revision = '17b949962f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_minutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_reunion', sa.Date(), nullable=False),
    sa.Column('asunto', sa.Text(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('acuerdos', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('cargo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_minutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('responsable', sa.Text(), nullable=False),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('estatus', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_minutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_commitments')
    op.drop_table('meeting_attendees')
    op.drop_table('meeting_minutes')
    # ### end Alembic commands ###
