"""fix relaciones sef

Revision ID: a610ec5a57a5
Revises: 2e46ee2bced6
Create Date: 2026-02-14 19:29:12.650039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a610ec5a57a5'
down_revision = '2e46ee2bced6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_unidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sef_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_solicitudes_sef_unidades_solicitud_id'))
        batch_op.create_index(batch_op.f('ix_solicitudes_sef_unidades_sef_id'), ['sef_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('solicitudes_sef_unidades_solicitud_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'solicitudes_sef', ['sef_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('solicitud_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_unidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitud_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solicitudes_sef_unidades_solicitud_id_fkey'), 'solicitudes_sef', ['solicitud_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_solicitudes_sef_unidades_sef_id'))
        batch_op.create_index(batch_op.f('ix_solicitudes_sef_unidades_solicitud_id'), ['solicitud_id'], unique=False)
        batch_op.drop_column('sef_id')

    # ### end Alembic commands ###
