"""agrega campos base solicitud

Revision ID: b5145fa8c6b8
Revises: bfff365cf5b6
Create Date: 2026-02-14 10:40:57.182819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5145fa8c6b8'
down_revision = 'bfff365cf5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.alter_column('rfc',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.alter_column('rfc',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
