"""crea catalogo_productos

Revision ID: b7a50dd79788
Revises: 9e2cdc50ca43
Create Date: 2026-02-18 23:52:37.367818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a50dd79788'
down_revision = '9e2cdc50ca43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_sef_contactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sef_id', sa.Integer(), nullable=False),
    sa.Column('nombre_contacto', sa.Text(), nullable=True),
    sa.Column('correo', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('numero_terminal_sef', sa.Text(), nullable=True),
    sa.Column('tipos_contacto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sef_id'], ['solicitudes_sef.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitudes_sef_usuarios_sef',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sef_id', sa.Integer(), nullable=False),
    sa.Column('unidad_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('perfil', sa.String(length=100), nullable=True),
    sa.Column('estatus', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['sef_id'], ['solicitudes_sef.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidad_id'], ['solicitudes_sef_unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_sef_usuarios_sef', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_sef_usuarios_sef_sef_id'), ['sef_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_usuarios_sef', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_sef_usuarios_sef_sef_id'))

    op.drop_table('solicitudes_sef_usuarios_sef')
    op.drop_table('solicitudes_sef_contactos')
    # ### end Alembic commands ###
