"""catalogos base

Revision ID: bb9b3ff8a7eb
Revises: c20c15ab7fa2
Create Date: 2026-02-16 03:34:13.135369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb9b3ff8a7eb'
down_revision = 'c20c15ab7fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_adhesiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_adhesiones_clave'))

    op.drop_table('catalogo_adhesiones')
    op.drop_table('system_params')
    op.drop_table('document_templates')
    op.drop_table('meeting_attendees')
    op.drop_table('meeting_minutes')
    op.drop_table('meeting_commitments')
    with op.batch_alter_table('catalogo_cpae', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cpae_descripcion'))

    with op.batch_alter_table('catalogo_etv', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_etv_nombre'))

    with op.batch_alter_table('catalogo_municipio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_municipio_entidad'))

    with op.batch_alter_table('catalogo_procesadora', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_proc_nombre'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_procesadora', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_proc_nombre'), ['nombre'], unique=False)

    with op.batch_alter_table('catalogo_municipio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_municipio_entidad'), ['entidad_id'], unique=False)

    with op.batch_alter_table('catalogo_etv', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_etv_nombre'), ['nombre'], unique=False)

    with op.batch_alter_table('catalogo_cpae', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_cpae_descripcion'), ['descripcion'], unique=False)

    op.create_table('meeting_commitments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('responsable', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('eta', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('estatus', sa.TEXT(), server_default=sa.text("'PENDIENTE'::text"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_minutes.id'], name=op.f('meeting_commitments_meeting_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meeting_commitments_pkey'))
    )
    op.create_table('meeting_minutes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('meeting_minutes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('fecha_reunion', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('asunto', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acuerdos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='meeting_minutes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('meeting_attendees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cargo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting_minutes.id'], name=op.f('meeting_attendees_meeting_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meeting_attendees_pkey'))
    )
    op.create_table('document_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_html', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('css', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('cascaron', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('document_templates_pkey')),
    sa.UniqueConstraint('slug', 'version', name=op.f('document_templates_slug_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('system_params',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('system_params_pkey'))
    )
    op.create_table('catalogo_adhesiones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('vigente_desde', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('vigente_hasta', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('catalogo_adhesiones_pkey'))
    )
    with op.batch_alter_table('catalogo_adhesiones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_adhesiones_clave'), ['clave'], unique=False)

    # ### end Alembic commands ###
