"""agrega campos base solicitud

Revision ID: bfff365cf5b6
Revises: db3fdb2bacf6
Create Date: 2026-02-14 10:40:12.166999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfff365cf5b6'
down_revision = 'db3fdb2bacf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfc', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('rfc')

    # ### end Alembic commands ###
