"""catalogos base

Revision ID: c20c15ab7fa2
Revises: 0a6ff328fd66
Create Date: 2026-02-15 19:12:48.768988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20c15ab7fa2'
down_revision = '0a6ff328fd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_etv', schema=None) as batch_op:
        batch_op.drop_column('clave')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_etv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clave', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
