"""agrega campos base solicitud

Revision ID: db3fdb2bacf6
Revises: 3c3c90cfe9f1
Create Date: 2026-02-14 10:18:27.464337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3fdb2bacf6'
down_revision = '3c3c90cfe9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_cliente', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('numero_contrato', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('razon_social', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes', schema=None) as batch_op:
        batch_op.drop_column('observaciones')
        batch_op.drop_column('razon_social')
        batch_op.drop_column('numero_contrato')
        batch_op.drop_column('numero_cliente')

    # ### end Alembic commands ###
