"""crea catalogo_productos

Revision ID: dbde8fa1d54f
Revises: 7a3c6534a4c3
Create Date: 2026-02-18 22:27:10.750708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbde8fa1d54f'
down_revision = '7a3c6534a4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_adhesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_adhesiones', schema=None) as batch_op:
        batch_op.create_index('idx_adhesiones_clave', ['clave'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalogo_adhesiones_clave'), ['clave'], unique=False)

    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_document_templates_active'), postgresql_where='(is_active = true)')

    op.drop_table('document_templates')
    op.drop_table('system_params')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_params',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('system_params_pkey'))
    )
    op.create_table('document_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_html', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('css', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('cascaron', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('updated_by', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('document_templates_pkey')),
    sa.UniqueConstraint('slug', 'version', name=op.f('document_templates_slug_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_document_templates_active'), ['slug'], unique=False, postgresql_where='(is_active = true)')

    with op.batch_alter_table('catalogo_adhesiones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_adhesiones_clave'))
        batch_op.drop_index('idx_adhesiones_clave')

    op.drop_table('catalogo_adhesiones')
    # ### end Alembic commands ###
