"""crea catalogo_productos

Revision ID: fe6a80402a6b
Revises: 88006ef60e31
Create Date: 2026-02-19 08:43:20.079118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6a80402a6b'
down_revision = '88006ef60e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_sef_firmantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_sef_firmantes_producto_id'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_sef_firmantes_sef_id'))

    op.drop_table('solicitudes_sef_firmantes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_sef_firmantes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sef_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('puesto', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('soeid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['catalogo_productos.id'], name=op.f('solicitudes_sef_firmantes_producto_id_fkey')),
    sa.ForeignKeyConstraint(['sef_id'], ['solicitudes_sef.id'], name=op.f('solicitudes_sef_firmantes_sef_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('solicitudes_sef_firmantes_pkey'))
    )
    with op.batch_alter_table('solicitudes_sef_firmantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_sef_firmantes_sef_id'), ['sef_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_sef_firmantes_producto_id'), ['producto_id'], unique=False)

    # ### end Alembic commands ###
